version: '3.7'

services:
  php-backend:
    image: edspc/php-fpm-alpine:${PHP_VERSION:-7.4}
    environment:
      - PHP_IDE_CONFIG=serverName=php-backend.docker
      - XDEBUG_CONFIG=remote_host=172.31.0.1 remote_port=9000 remote_enable=on idekey=PHPSTORM
    volumes:
      - ./data:/var/www:Z
      - ./docker/php-backend/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./docker/php-backend/etc/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro

  database:
    image: mariadb:${MARIADB_VERSION:-10.2}
    environment:
      - MYSQL_ROOT_PASSWORD=azzTPLYbnTsRUG8EHHTn
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: edspc/nginx-alpine
    ports:
      - 80:80
    depends_on:
      - php-backend
    volumes:
      - ./data:/var/www:Z
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16

volumes:
  db-data:
